config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "static_pages#index"
  resources "static_pages"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    if params[:user_id]
      @user_photos = get_photo_urls(params[:user_id])
    end
  end

  private

  def get_photo_urls(user_id)
    api_key = Rails.application.credentials.dig(:flickr, :api_key)
    photo_urls = []
    get_photo_ids(user_id).each do |photo_id|
      url = "https://www.flickr.com/services/rest/?method=flickr.photos.getSizes&api_key=#{api_key}&photo_id=#{photo_id}&format=json&nojsoncallback=1"
      response = HTTParty.get(url)
      photo_urls << response["sizes"]["size"][5]["source"]
    end
    photo_urls
  end

  def get_photo_ids(user_id)
    api_key = Rails.application.credentials.dig(:flickr, :api_key)
    url = "https://api.flickr.com/services/rest/?method=flickr.people.getPublicPhotos&api_key=#{api_key}&user_id=#{user_id}&format=json&nojsoncallback=1"
    response = HTTParty.get(url)
    photo_ids = []
    photos_info = response["photos"]["photo"]
    photos_info.each do |photo_info|
      photo_info.each do |key, value|
        if key == "id"
          photo_ids << value
          next
        end
      end
    end
    photo_ids
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Image Book" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<%= form_with url: static_pages_path, method: :get do |form| %>
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
    <%= form.submit %>
<% end %>

<% if @user_photos %>
    <% @user_photos.each do |photo_url| %>
        <%= image_tag(photo_url, alt: "flickr image")%>
    <% end %>
<% end %>